site_name: ComputeStacks Documentation
theme: 
  name: material
  custom_dir: overrides
  features:
    - instant
    - tabs
  favicon: images/favicon.png
  icon:
    logo: fontawesome/duotone/books
  palette:
    scheme: slate
    primary: blue
    accent: orange
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - meta
  - smarty
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - search
  - macros:
      include_dir: snippets
