site_name: ComputeStacks Documentation
theme: 
  name: material
  custom_dir: overrides
  features:    
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  favicon: images/favicon.png
  icon:
    logo: fontawesome/duotone/books
  palette:
    scheme: slate
    primary: blue
    accent: orange
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - meta
  - smarty
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
plugins:
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - search
  - macros:
      include_dir: snippets
nav:
  - Home: 'index.md'
  - Getting Started:
    - Overview: 'getting_started/index.md'
    - Architecture: 'getting_started/architecture_overview.md'
    - Notifications: 'getting_started/notifications.md'    
    - Installation:
      - Plan: 'getting_started/installation/0_requirements.md'
      - Prepare: 'getting_started/installation/1_prepare.md'
      - Run: 'getting_started/installation/2_perform.md'
      - Finalize: 'getting_started/installation/3_finalize.md'
    - Integrations:
      - cPanel: 'getting_started/integrations/cpanel_plugin.md'
      - WebHooks: 'getting_started/integrations/webhooks.md'
      - WHMCS: 'getting_started/integrations/whmcs_plugin.md'
  - Admin Guide:
    - Overview: 'admin_guide/index.md'
    - Billing:
      - Overview: 'admin_guide/billing/index.md'
      - Billing Plans: 'admin_guide/billing/billing_plans.md'
      - Setup Free Trials: 'admin_guide/billing/free_trial.md'
      - Handle Invoicing & Payments: 'admin_guide/billing/integrations.md'
    - Cluster Management:
      - Resource Management: 'admin_guide/cluster_management/resource_management.md'
      - Rename Region: 'admin_guide/cluster_management/change_region_name.md'
      - Controller Database: 'admin_guide/cluster_management/cs_database.md'
      - Load Balancer: 'admin_guide/cluster_management/load_balancer.md'
    - System Administration:
      - Update Agent: 'admin_guide/sysadmin/upgrade_agent.md'
    - Custom Integrations:
      - API Only: 'admin_guide/custom_integration/full_api.md'
  - User Guide:
    - Overview: 'user_guide/index.md'
    - Backups: 'user_guide/backups.md'
    - Developer Tools: 'user_guide/developer-tools.md'
    - Container Images:
      - ElasticSearch: 'user_guide/container_images/elastic-search.md'
      - Redis: 'user_guide/container_images/redis.md'
      - Wordpress: 
          - Overview: 'user_guide/container_images/wordpress.md'
          - Apache to LiteSpeed: 'user_guide/container_images/wordpress_apache.md'
      - WHMCS: 'user_guide/container_images/whmcs.md'
    - Core Concepts:
      - Sending Mail: 'user_guide/core-concepts/mail.md'
      - SSH & File Access: 'user_guide/core-concepts/ssh.md'
    - How To:
      - Building Images: 'user_guide/how-to/building-images.md'
      - Cloning Projects: 'user_guide/how-to/clone-project.md'
      - Migrating Existing Application: 'user_guide/how-to/moving.md'
    - Third Party:
      - Cloudflare: 'user_guide/third-party/cloudflare.md'
  - Admin API:
    - Overview: 'admin_api/index.md'
    - Container Services: 'admin_api/container_services/index.md'
    - Images: 'admin_api/images/index.md'
    - Projects: 'admin_api/projects/index.md'
    - Billing: 
      - Overview: 'admin_api/billing/index.md'
      - Products: 'admin_api/billing/products.md'
      - Billing Plans: 'admin_api/billing/billing_plans.md'
      - Billing Resources: 'admin_api/billing/resources.md'
      - Billing Phases: 'admin_api/billing/phases.md'
      - Resource Prices: 'admin_api/billing/prices.md'
    - Infrastructure:
      - Overview: 'admin_api/infrastructure/index.md'
      - Regions: 'admin_api/infrastructure/locations.md'
      - Availability Zones: 'admin_api/infrastructure/regions.md'
      - Nodes: 'admin_api/infrastructure/nodes.md'
    - Networking:
      - Domains: 'admin_api/networking/domains.md'
      - Ingress Rules: 'admin_api/networking/ingress_rules.md'
    - Subscription Management: 
      - Subscriptions: 'admin_api/subscriptions/subscriptions.md'
      - Usage: 'admin_api/subscriptions/usage.md'
    - User Management:
      - Users: 'admin_api/users/index.md'
      - Groups: 'admin_api/users/user_groups.md'
  - User API:
    - Overview: 'user_api/index.md'
    - Collaborations:
      - Overview: 'user_api/latest/collaborations/index.md'
      - Images: 'user_api/latest/collaborations/images.md'
      - Projects: 'user_api/latest/collaborations/projects.md'
      - Registry: 'user_api/latest/collaborations/registry.md'
      - Zones: 'user_api/latest/collaborations/zones.md'
