site_name: ComputeStacks Documentation
theme: 
  name: material
  custom_dir: overrides
  features:    
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  favicon: images/favicon.png
  icon:
    logo: fontawesome/duotone/books
  palette:
    scheme: slate
    primary: blue
    accent: orange
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - meta
  - smarty
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
plugins:
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - search
  - macros:
      include_dir: snippets
nav:
  - Home: 'index.md'
  - Getting Started:
    - Overview: 'getting_started/index.md'
    - Architecture: 'getting_started/architecture_overview.md'
    - Notifications: 'getting_started/notifications.md'    
    - Installation:
      - Plan: 'getting_started/installation/0_requirements.md'
      - Prepare: 'getting_started/installation/1_prepare.md'
      - Run: 'getting_started/installation/2_perform.md'
      - Finalize: 'getting_started/installation/3_finalize.md'
    - Integrations:
      - cPanel: 'getting_started/integrations/cpanel_plugin.md'
      - WebHooks: 'getting_started/integrations/webhooks.md'
      - WHMCS: 'getting_started/integrations/whmcs_plugin.md'
  - Admin Guide:
    - Overview: 'admin_guide/index.md'
    - Billing:
      - Overview: 'admin_guide/billing/index.md'
      - Billing Plans: 'admin_guide/billing/billing_plans.md'
      - Setup Free Trials: 'admin_guide/billing/free_trial.md'
      - Handle Invoicing & Payments: 'admin_guide/billing/integrations.md'
    - Cluster Management:
      - Resource Management: 'admin_guide/cluster_management/resource_management.md'
      - Rename Region: 'admin_guide/cluster_management/change_region_name.md'
      - Controller Database: 'admin_guide/cluster_management/cs_database.md'
      - Load Balancer: 'admin_guide/cluster_management/load_balancer.md'
    - System Administration:
      - Controller Backup: 'admin_guide/sysadmin/controller_backups.md'
      - Update Agent: 'admin_guide/sysadmin/upgrade_agent.md'
    - Custom Integrations:
      - API Only: 'admin_guide/custom_integration/full_api.md'
  - User Guide:
    - Overview: 'user_guide/index.md'
    - Backups: 'user_guide/backups.md'
    - Developer Tools: 'user_guide/developer-tools.md'
    - Container Images:
      - ElasticSearch: 'user_guide/container_images/elastic-search.md'
      - Redis: 'user_guide/container_images/redis.md'
      - Wordpress: 
          - Overview: 'user_guide/container_images/wordpress.md'
          - Apache to LiteSpeed: 'user_guide/container_images/wordpress_apache.md'
      - WHMCS: 'user_guide/container_images/whmcs.md'
    - Core Concepts:
      - Sending Mail: 'user_guide/core-concepts/mail.md'
      - SSH & File Access: 'user_guide/core-concepts/ssh.md'
    - How To:
      - Building Images: 'user_guide/how-to/building-images.md'
      - Cloning Projects: 'user_guide/how-to/clone-project.md'
      - Migrating Existing Application: 'user_guide/how-to/moving.md'
    - Third Party:
      - Cloudflare: 'user_guide/third-party/cloudflare.md'
  - Admin API:
    - Overview: 'admin_api/index.md'
    - Container Services: 'admin_api/latest/container_services/index.md'    
    - Billing: 
      - Overview: 'admin_api/latest/billing/index.md'
      - Products: 'admin_api/latest/billing/products.md'
      - Billing Plans: 'admin_api/latest/billing/billing_plans.md'
      - Billing Resources: 'admin_api/latest/billing/resources.md'
      - Billing Phases: 'admin_api/latest/billing/phases.md'
      - Resource Prices: 'admin_api/latest/billing/prices.md'
    - DNS:
      - Overview: 'admin_api/latest/zones/index.md'
      - Collaborations: 'admin_api/latest/zones/collaborators.md'
    - Infrastructure:
      - Overview: 'admin_api/latest/infrastructure/index.md'
      - Regions: 'admin_api/latest/infrastructure/locations.md'
      - Availability Zones: 'admin_api/latest/infrastructure/regions.md'
      - Nodes: 'admin_api/latest/infrastructure/nodes.md'
    - Images: 
      - Overview: 'admin_api/latest/images/index.md'
      - Collaborations: 'admin_api/latest/images/collaborations.md'
    - Networking:
      - Domains: 'admin_api/latest/networking/domains.md'
      - Ingress Rules: 'admin_api/latest/networking/ingress_rules.md'
    - Projects:
      - Overview: 'admin_api/latest/projects/index.md'
      - Collaborations: 'admin_api/latest/projects/collaborators.md'
    - Registry:
      - Overview: 'admin_api/latest/registry/index.md'
      - Collaborations: 'admin_api/latest/registry/collaborators.md'
    - Subscription Management: 
      - Subscriptions: 'admin_api/latest/subscriptions/subscriptions.md'
      - Usage: 'admin_api/latest/subscriptions/usage.md'
    - User Management:
      - Users: 'admin_api/latest/users/index.md'
      - Groups: 'admin_api/latest/users/user_groups.md'
      - SSH Keys: 'admin_api/latest/users/ssh_keys.md'
  - User API:
    - Overview: 'user_api/latest/index.md'
    - Collaborators: 'user_api/latest/collaborations/index.md'
    - Containers: 'user_api/latest/containers/index.md'
    - Container Registry: 
      - Overview: 'user_api/latest/container_registry/index.md'
      - Collaborators: 'user_api/latest/container_registry/collaborations.md'
    - Container Services: 
      - Overview: 'user_api/latest/container_services/index.md'
      - Metadata: 'user_api/latest/container_services/metadata.md'
      - Resources: 'user_api/latest/container_services/resources.md'
      - SSL: 'user_api/latest/container_services/ssl.md'
    - Domains: 'user_api/latest/domains/index.md'
    - DNS: 
      - Overview: 'user_api/latest/zones/index.md'
      - Collaborators: 'user_api/latest/zones/collaborations.md'
    - Events: 'user_api/latest/events/index.md'
    - Images:
      - Overview: 'user_api/latest/images/index.md'
      - Collaborators: 'user_api/latest/images/collaborations.md'
      - Providers: 'user_api/latest/images/providers.md'
      - Parameters:
        - Env: 'user_api/latest/images/params/env.md'
        - Ingress: 'user_api/latest/images/params/ingress.md'
        - Relationships: 'user_api/latest/images/params/relationships.md'
        - Settings: 'user_api/latest/images/params/settings.md'
        - Volumes: 'user_api/latest/images/params/volumes.md'
    - Load Balancers: 'user_api/latest/load_balancers/index.md'
    - Locations: 'user_api/latest/locations/index.md'
    - Networks:
      - Ingress Rules: 'user_api/latest/network/index.md'
    - Orders: 'user_api/latest/orders/index.md'
    - Products: 'user_api/latest/products/index.md'
    - Profile: 
      - Overview: 'user_api/latest/user/index.md'
      - SSH Keys: 'user_api/latest/user/ssh.md'
    - Projects: 
      - Overview: 'user_api/latest/projects/index.md'
      - Collaborators: 'user_api/latest/projects/collaborations.md'
      - Resources: 'user_api/latest/projects/resources.md'
    - Subscriptions: 
      - Overview: 'user_api/latest/subscriptions/index.md'
      - Billing Events: 'user_api/latest/subscriptions/billing_events.md'
      - Usage: 'user_api/latest/subscriptions/usage.md'
    - Volumes: 
      - Overview: 'user_api/latest/volumes/index.md'
      - Backups: 'user_api/latest/volumes/backup.md'
